### PR TITLE
feat: support css variables as theme color value

### PR DESCRIPTION
**Pull request by TD-4242**
I can clean up the comments if not needed, but this fixed an issue of magicbell ui not respecting my sites theme css variables in some cases.

### CODE REVIEW

**Review by smeijer — APPROVED** [review]
Nice one! The color system can use some improvement overall, but this is a great change to make it a bit more flexible.

Thank you, much appreciated.

**Comment by smeijer** [comment]
I'll push a `changeset` to this pr in the morning so we can get it merged. (you're also welcome to do so if you're faster than me)

**Comment by TD-4242** [comment]
Thanks, I haven't used `changeset` is it just the markdown file?

**Comment by unamashana** [comment]
@TD-4242 thanks for the PR. Here is an example of the `changeset` @smeijer mentioned - https://github.com/magicbell-io/magicbell-js/pull/86/files#diff-2642cff9fff816208ea17ed7c60684698fe3a7ede574dc0a3d10fb14e2fef356

**Comment by smeijer** [comment]
Yes, the changeset is indeed just that generated markdown file that you get when running `yarn changeset` in the root of this repo. That markdown file is then committed, and merged to `main`, where our CI will pick it up and use it to generate changelogs, bump package versions, and publish the releases. I think we should expand [that part of the readme](https://github.com/magicbell-io/magicbell-js/#pull-requests) a bit, as changesets sound very exciting, but are - in the scope of a pr - really not that complex at all 🙂 

I've [pushed one to this pull](https://github.com/magicbell-io/magicbell-js/pull/88/commits/1fb6df2b343848f0125fd66bea600a1b1e648fc5), let's get it merged!

Thanks again!

**Pull request merged**
